spring:
  kafka:
    template:
      default-topic: kafkaReplies
    listener:
      ack-mode: RECORD
    bootstrap-servers: "localhost:9092"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id: "test"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      security:
#        protocol: PLAINTEXT
#logging:
#  level:
#    org.apache.kafka: TRACE